### ISSUE TITLE
Map URLs to fragments

### ISSUE THREAD

**Issue by CaptainCodeman** [CaptainCodeman/prpl-server-go#6]
The current prpl-server logic doesn't push as much as it could / should.

The first request is likely to be for a routed URL, not one of the source files, app shell or the entrypoint (index.html). But these don't exist in the manifest so the push of critical resources doesn't happen until the subsequent requests are made, which slightly defeats the purpose / isn't as optimized as it could be.

With a URL -> fragment mapping, a request for `/view1` could have the `src/my-app.html` and `src/my-view1.html` assets pushed (plus the webcomponents loader if required for the browser).

See: https://www.captaincodeman.com/2017/03/28/polymer-2-0-build-http-2-server-push

**Comment by silenceisgolden** [comment]
Smashing magazine did a thing with cookies for critical CSS I think, where they would only include the critical CSS block if the visitor was a new user. It might be interesting to investigate if this method would work for only pushing the shell/etc. for a new visitor rather than a returning visitor visiting a deep link. This assumes that proper cache busting is already set up.

**Comment by CaptainCodeman** [comment]
That sounds like CASPer (Cache Aware Server Push) using a bloom filter in a cookie.

I've experimented with this a bit more and have it working better but at the expense of invalidating the entire app in return for making all the files cacheable. More details [here](https://github.com/Polymer/prpl-server-node/issues/41)
